use nestbot::{
    application::App,
    config::Config,
    domain::{ClaimRecord, Entry, JobPayload, TransferMode},
    interfaces::bot,
    storage::{Store, vault::Vault},
};
use std::sync::Arc;

fn fixture() -> (tempfile::TempDir, Store, Config) {
    let dir = tempfile::tempdir().unwrap();
    let vault =
        Arc::new(Vault::open(&dir.path().join("master.key"), "synthetic-password").unwrap());
    let store = Store::open(&dir.path().join("test.sqlite"), vault, 1024, 20).unwrap();
    let mut config = Config {
        default_target: "-100123456789".into(),
        ..Default::default()
    };
    config.telegram.bot_token_env = "NESTBOT_BATCH_TEST_DISABLED_BOT".into();
    (dir, store, config)
}

async fn batch(store: &Store) -> String {
    store
        .save_page(
            "test",
            1,
            None,
            (1..=37)
                .map(|n| Entry {
                    key: format!("synthetic-key-{n}"),
                    ..Default::default()
                })
                .collect(),
        )
        .await
        .unwrap()
}

#[tokio::test]
async fn name_id_imported_alias_and_python_filename_select_only_entry_25() {
    let (_dir, store, config) = fixture();
    let id = batch(&store).await;
    // Generated by the original Python vault.batch_name('test','synthetic-password').
    let legacy = "k_7828cb5fdfadaf9fdf654ed5.bin";
    assert_eq!(
        store
            .resolve_batch(legacy, Some("synthetic-password"))
            .await
            .unwrap(),
        id
    );
    assert_eq!(store.resolve_batch(legacy, None).await.unwrap(), id);
    store
        .set_preference("batch_alias:k_imported.bin", &id)
        .await
        .unwrap();
    let app = App::new(config, store.clone()).unwrap();
    for name in ["test", id.as_str(), legacy, "k_imported.bin"] {
        let reply = bot::command(&app, 42, &format!("/batch {name} 25 25"), None)
            .await
            .unwrap();
        assert!(reply.contains("已排队"), "{reply}");
        let job = store.next_job().await.unwrap().unwrap();
        assert!(
            matches!(&job.payload,JobPayload::Transfer {batch:Some(b),start:25,end:Some(25),..} if b==&id)
        );
        app.execute(&job, &tokio_util::sync::CancellationToken::new())
            .await
            .unwrap();
        assert_eq!(store.report(&job.summary.id).await.unwrap().failed_keys, 1);
        assert_eq!(store.batch_next_pending(&id).await.unwrap(), Some(1));
        store
            .finish(&job.summary.id, "completed", None, None)
            .await
            .unwrap();
    }
}

#[tokio::test]
async fn manual_progress_needs_no_target_is_exact_can_be_lowered_and_survives_reopen() {
    let (dir, store, mut config) = fixture();
    config.default_target.clear();
    let id = batch(&store).await;
    let other = store
        .save_page(
            "other",
            1,
            None,
            vec![Entry {
                key: "synthetic-key-1".into(),
                ..Default::default()
            }],
        )
        .await
        .unwrap();
    store
        .save_claim(
            "synthetic-key-20",
            &ClaimRecord {
                status: "done".into(),
                files: 1,
                failed: 0,
                file_ids: [("d".into(), 20)].into_iter().collect(),
            },
        )
        .await
        .unwrap();
    let app = App::new(config, store.clone()).unwrap();
    let reply = bot::command(&app, 42, "/batch test progress 11", None)
        .await
        .unwrap();
    assert!(reply.contains("第 12 条"));
    assert!(store.jobs(20, 0).await.unwrap().is_empty());
    assert_eq!(store.batch_next_pending(&id).await.unwrap(), Some(12));
    assert_eq!(store.batch_override(&id, 20).await.unwrap(), Some(false));
    assert_eq!(store.batch_override(&other, 1).await.unwrap(), None);
    assert!(
        store
            .claim_record("synthetic-key-20")
            .await
            .unwrap()
            .complete(None)
    );
    let list = bot::command(&app, 42, "/batch", None).await.unwrap();
    assert!(list.contains("test：37 条，已转 11"));
    let reopened = Store::open(
        &dir.path().join("test.sqlite"),
        store.vault.clone(),
        1024,
        20,
    )
    .unwrap();
    assert_eq!(reopened.batch_next_pending(&id).await.unwrap(), Some(12));
    bot::command(&app, 42, "/batch test progress 3", None)
        .await
        .unwrap();
    assert_eq!(reopened.batch_next_pending(&id).await.unwrap(), Some(4));
    bot::command(&app, 42, "/batch test progress 0", None)
        .await
        .unwrap();
    assert_eq!(reopened.batch_next_pending(&id).await.unwrap(), Some(1));
    let invalid = bot::command(&app, 42, "/batch test progress 38", None)
        .await
        .unwrap();
    assert!(invalid.contains("不能超过"));
    assert_eq!(reopened.batch_next_pending(&id).await.unwrap(), Some(1));
}

#[tokio::test]
async fn default_batch_and_continue_start_at_12_after_setting_11() {
    let (_dir, store, config) = fixture();
    let id = batch(&store).await;
    let app = App::new(config, store.clone()).unwrap();
    bot::command(&app, 42, "/batch test progress 11", None)
        .await
        .unwrap();
    for command in ["/batch test", "/batch continue"] {
        bot::command(&app, 42, command, None).await.unwrap();
        let job = store.next_job().await.unwrap().unwrap();
        assert!(matches!(&job.payload,JobPayload::Transfer {batch:Some(b),start:12,..} if b==&id));
        store
            .finish(&job.summary.id, "completed", None, None)
            .await
            .unwrap();
    }
    bot::command(&app, 42, "/batch test progress 37", None)
        .await
        .unwrap();
    assert_eq!(store.batch_next_pending(&id).await.unwrap(), None);
    assert!(
        bot::command(&app, 42, "/batch test", None)
            .await
            .unwrap()
            .contains("已全部")
    );
    assert!(store.next_job().await.unwrap().is_none());
    bot::command(&app, 42, "/batch test redo", None)
        .await
        .unwrap();
    assert!(matches!(
        store.next_job().await.unwrap().unwrap().payload,
        JobPayload::Transfer {
            start: 1,
            redo: true,
            ..
        }
    ));
}

#[tokio::test]
async fn a_queued_full_range_respects_manual_progress_without_connecting_for_done_keys() {
    let (_dir, store, config) = fixture();
    let id = batch(&store).await;
    store.set_batch_progress(&id, 11).await.unwrap();
    let app = App::new(config, store.clone()).unwrap();
    app.enqueue(
        JobPayload::Transfer {
            options: nestbot::domain::TransferOptions {
                confirmed: true,
                ..Default::default()
            },
            keys: vec![],
            batch: Some(id.clone()),
            start: 1,
            end: None,
            mode: TransferMode::Copy,
            target: "-100123456789".into(),
            redo: false,
            dry_run: false,
        },
        Some(42),
        None,
    )
    .await
    .unwrap();
    let job = store.next_job().await.unwrap().unwrap();
    app.execute(&job, &tokio_util::sync::CancellationToken::new())
        .await
        .unwrap();
    let report = store.report(&job.summary.id).await.unwrap();
    assert_eq!(report.skipped_keys, 11);
    assert_eq!(report.failed_keys, 26);
    assert_eq!(store.batch_next_pending(&id).await.unwrap(), Some(12));
    assert!(
        store
            .set_batch_progress(&id, 5)
            .await
            .unwrap_err()
            .to_string()
            .contains("batch_busy")
    );
    assert_eq!(store.batch_override(&id, 11).await.unwrap(), Some(true));
}

#[tokio::test]
async fn final_claim_and_batch_completion_commit_atomically() {
    let (_dir, store, _config) = fixture();
    let id = batch(&store).await;
    store.set_batch_progress(&id, 0).await.unwrap();
    let record = ClaimRecord {
        status: "done".into(),
        files: 1,
        failed: 0,
        file_ids: [("d".into(), 1)].into_iter().collect(),
    };
    store.call(|c| {c.execute_batch("CREATE TRIGGER reject_completion BEFORE DELETE ON batch_progress BEGIN SELECT RAISE(ABORT,'synthetic failure'); END;")?;Ok(())}).await.unwrap();
    assert!(
        store
            .save_claim_for_batch("synthetic-key-1", &record, Some((&id, 1)))
            .await
            .is_err()
    );
    assert!(
        !store
            .claim_record("synthetic-key-1")
            .await
            .unwrap()
            .complete(None)
    );
    assert_eq!(store.batch_override(&id, 1).await.unwrap(), Some(false));
    store
        .call(|c| {
            c.execute_batch("DROP TRIGGER reject_completion")?;
            Ok(())
        })
        .await
        .unwrap();
    store
        .save_claim_for_batch("synthetic-key-1", &record, Some((&id, 1)))
        .await
        .unwrap();
    assert!(
        store
            .claim_record("synthetic-key-1")
            .await
            .unwrap()
            .complete(None)
    );
    assert_eq!(store.batch_override(&id, 1).await.unwrap(), None);
    assert_eq!(store.batch_next_pending(&id).await.unwrap(), Some(2));
}
