'use strict';
const $=id=>document.getElementById(id);
let csrf='',status={},selectedBatch='',jobsOffset=0,batchesOffset=0,entriesOffset=0,events=null,refreshTimer=null;
const labels={queued:'排队',waiting:'等待',running:'运行中',partial:'部分完成',completed:'完成',failed:'失败',cancelled:'已停止',interrupted:'中断',review:'待核对',cancelling:'停止中'};
function notice(text){$('notice').textContent=text;$('notice').style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>{$('notice').style.display='none';},5000);}
async function api(url,method='GET',body){const response=await fetch(url,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':csrf}:{})},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok){if(response.status===401&&url!=='/api/login')showLogin();throw new Error(value.error||'请求失败');}return value;}
function text(value,tag='span'){const node=document.createElement(tag);node.textContent=String(value??'');return node;}
function button(label,action){const node=text(label,'button');node.addEventListener('click',()=>Promise.resolve().then(action).catch(e=>notice(e.message)));return node;}
function table(headers,rows){const wrap=document.createElement('div');wrap.className='table-wrap';if(!rows.length){const empty=text('暂无记录','div');empty.className='empty';wrap.append(empty);return wrap;}const t=document.createElement('table'),head=document.createElement('thead'),hr=document.createElement('tr');headers.forEach(h=>hr.append(text(h,'th')));head.append(hr);t.append(head);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const cell of row){const td=document.createElement('td');td.append(cell instanceof Node?cell:text(cell));tr.append(td);}body.append(tr);}t.append(body);wrap.append(t);return wrap;}
function showLogin(){csrf='';if(events){events.close();events=null;}$('workspace').hidden=true;$('login-panel').hidden=false;$('logout').hidden=true;$('connection').textContent='未登录';}
async function start(){const session=await api('/api/session');csrf=session.csrf;$('login-panel').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('connection').textContent='已连接';await refresh();events=new EventSource('/api/events');events.addEventListener('job',scheduleRefresh);events.addEventListener('resync',scheduleRefresh);events.onopen=()=>{$('connection').textContent='已连接';scheduleRefresh();};events.onerror=()=>{$('connection').textContent='重新连接中';};}
function scheduleRefresh(){if(refreshTimer)return;refreshTimer=setTimeout(()=>{refreshTimer=null;refresh().catch(e=>notice(e.message));},1500);}
async function refresh(){status=await api('/api/status');$('setting-target').value=status.target;$('setting-mode').value=status.mode;for(const input of document.querySelectorAll('.target-input'))if(!input.value)input.value=status.target;$('limits').textContent=JSON.stringify(status.limits,null,2);const cards=[['默认模式',status.mode],['当前目标',status.target||'未设置'],['常驻内存',status.memory_rss_bytes?(status.memory_rss_bytes/1048576).toFixed(1)+' MiB':'当前平台未提供'],['队列容量',status.limits.max_queue]];$('stats').replaceChildren(...cards.map(([label,value])=>{const card=document.createElement('div');card.className='card';card.append(text(label));const v=text(value,'div');v.className='value';card.append(v);return card;}));renderJobs('overview-jobs',status.jobs);if(!$('tasks').hidden)await loadJobs();if(!$('vault').hidden)await loadBatches();if(!$('logs').hidden)await loadLogs();}
function renderJobs(id,jobs){const rows=jobs.map(job=>{const badge=text(labels[job.status]||job.status);badge.className='badge '+job.status;const controls=document.createElement('div');if(['queued','waiting','running','interrupted'].includes(job.status))controls.append(button('停止',async()=>{await api('/api/jobs/'+job.id+'/cancel','POST',{});await refresh();}));if(['failed','cancelled','interrupted','partial'].includes(job.status))controls.append(button('重试',async()=>{await api('/api/jobs/'+job.id+'/retry','POST',{});await refresh();}));if(job.status==='review')controls.append(button('核对后重试',async()=>{if(!confirm('请先检查目标是否已收到文件。继续重试可能产生重复副本。'))return;await api('/api/jobs/'+job.id+'/retry','POST',{allow_uncertain:true});await refresh();}));return [text(job.id.slice(0,8),'code'),job.kind,badge,job.phase+' '+job.completed+(job.total!==null?'/'+job.total:''),job.error_code||'—',controls];});$(id).replaceChildren(table(['任务','类型','状态','进度','错误','操作'],rows));}
async function loadJobs(){renderJobs('jobs',await api('/api/jobs?limit=50&offset='+jobsOffset));}
async function loadBatches(){const batches=await api('/api/batches?limit=50&offset='+batchesOffset);$('batches').replaceChildren(table(['批次','条目','页码','操作'],batches.map(b=>[text(b.id.slice(0,16),'code'),b.entries,b.page,button('查看',async()=>{selectedBatch=b.id;entriesOffset=0;$('batch-detail').hidden=false;await loadEntries();})])));}
async function loadEntries(){const result=await api('/api/batches/'+selectedBatch+'/entries?limit=50&offset='+entriesOffset);$('batch-title').textContent=result.keyword;$('entries').replaceChildren(table(['序号','密钥','描述','文件数'],result.entries.map(row=>[row.seq,row.entry.key,row.entry.description,row.entry.file_count??'未知'])));}
async function loadLogs(){const jobs=await api('/api/logs');$('log-list').replaceChildren(table(['时间','任务','状态','代码'],jobs.map(j=>[new Date(j.updated_at*1000).toLocaleString(),j.id.slice(0,8),labels[j.status]||j.status,j.error_code||'ok'])));}
function form(id,handler){$(id).addEventListener('submit',async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('button[type="submit"],button');submit.disabled=true;try{await handler(new FormData(event.currentTarget));}catch(error){notice(error.message);}finally{submit.disabled=false;}});}
form('login-form',async data=>{const result=await api('/api/login','POST',{password:data.get('password')});csrf=result.csrf;$('login-form').reset();await start();});
form('search-form',async data=>{const result=await api('/api/jobs','POST',{kind:'search',keyword:data.get('keyword'),pages:data.get('pages')?Number(data.get('pages')):null,sort:data.get('sort')||null,resume:data.has('resume')});notice('搜索已排队：'+result.id.slice(0,8));await loadJobs();});
form('transfer-form',async data=>{const result=await api('/api/jobs','POST',{kind:'transfer',keys:data.get('keys').split(/\s+/).filter(Boolean),batch:null,start:1,end:null,mode:data.get('mode'),target:data.get('target'),redo:false,dry_run:data.has('dry_run')});notice('转存已排队：'+result.id.slice(0,8));await loadJobs();});
form('batch-form',async data=>{const result=await api('/api/jobs','POST',{kind:'transfer',keys:[],batch:selectedBatch,start:Number(data.get('start'))||1,end:data.get('end')?Number(data.get('end')):null,mode:data.get('mode'),target:data.get('target'),redo:false,dry_run:false});notice('批量任务已排队：'+result.id.slice(0,8));});
form('settings-form',async data=>{await api('/api/preferences','POST',{name:'target',value:data.get('target')});await api('/api/preferences','POST',{name:'mode',value:data.get('mode')});notice('默认设置已保存');await refresh();});
for(const node of document.querySelectorAll('nav button'))node.addEventListener('click',async()=>{for(const page of document.querySelectorAll('.page'))page.hidden=page.id!==node.dataset.page;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('selected',b===node);try{await refresh();}catch(e){notice(e.message);}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout','POST',{});}finally{showLogin();}});
$('refresh-jobs').addEventListener('click',()=>loadJobs().catch(e=>notice(e.message)));
$('clear-queue').addEventListener('click',async()=>{if(!confirm('清空所有排队与等待任务？'))return;try{await api('/api/queue/clear','POST',{});await loadJobs();}catch(e){notice(e.message);}});
for(const [name,loader] of [['jobs',loadJobs],['batches',loadBatches],['entries',loadEntries]])for(const direction of ['prev','next'])$(name+'-'+direction).addEventListener('click',()=>{const delta=direction==='next'?50:-50;if(name==='jobs')jobsOffset=Math.max(0,jobsOffset+delta);if(name==='batches')batchesOffset=Math.max(0,batchesOffset+delta);if(name==='entries')entriesOffset=Math.max(0,entriesOffset+delta);loader().catch(e=>notice(e.message));});
start().catch(()=>showLogin());
